server:
  port: 8092

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  application:
    name: consumer-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    # 服务拉取间隔默认30S
    registry-fetch-interval-seconds: 30